// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package com.kafka.demo.proto;

public final class AppointmentProtos {
  private AppointmentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Weekday}
   */
  public enum Weekday
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUNDAY = 0;</code>
     */
    SUNDAY(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURSDAY = 4;</code>
     */
    THURSDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    ;

    /**
     * <code>SUNDAY = 0;</code>
     */
    public static final int SUNDAY_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURSDAY = 4;</code>
     */
    public static final int THURSDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Weekday valueOf(int value) {
      return forNumber(value);
    }

    public static Weekday forNumber(int value) {
      switch (value) {
        case 0: return SUNDAY;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURSDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Weekday>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Weekday> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Weekday>() {
            public Weekday findValueByNumber(int number) {
              return Weekday.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kafka.demo.proto.AppointmentProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final Weekday[] VALUES = values();

    public static Weekday valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Weekday(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Weekday)
  }

  public interface AppointmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Appointment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string appointmentId = 1;</code>
     */
    boolean hasAppointmentId();
    /**
     * <code>required string appointmentId = 1;</code>
     */
    java.lang.String getAppointmentId();
    /**
     * <code>required string appointmentId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppointmentIdBytes();

    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>required .Weekday weekday = 3;</code>
     */
    boolean hasWeekday();
    /**
     * <code>required .Weekday weekday = 3;</code>
     */
    com.kafka.demo.proto.AppointmentProtos.Weekday getWeekday();
  }
  /**
   * Protobuf type {@code Appointment}
   */
  public  static final class Appointment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Appointment)
      AppointmentOrBuilder {
    // Use Appointment.newBuilder() to construct.
    private Appointment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Appointment() {
      appointmentId_ = "";
      userName_ = "";
      weekday_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Appointment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              appointmentId_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userName_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.kafka.demo.proto.AppointmentProtos.Weekday value = com.kafka.demo.proto.AppointmentProtos.Weekday.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                weekday_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kafka.demo.proto.AppointmentProtos.internal_static_Appointment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kafka.demo.proto.AppointmentProtos.internal_static_Appointment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kafka.demo.proto.AppointmentProtos.Appointment.class, com.kafka.demo.proto.AppointmentProtos.Appointment.Builder.class);
    }

    private int bitField0_;
    public static final int APPOINTMENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appointmentId_;
    /**
     * <code>required string appointmentId = 1;</code>
     */
    public boolean hasAppointmentId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string appointmentId = 1;</code>
     */
    public java.lang.String getAppointmentId() {
      java.lang.Object ref = appointmentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appointmentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appointmentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppointmentIdBytes() {
      java.lang.Object ref = appointmentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEEKDAY_FIELD_NUMBER = 3;
    private int weekday_;
    /**
     * <code>required .Weekday weekday = 3;</code>
     */
    public boolean hasWeekday() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Weekday weekday = 3;</code>
     */
    public com.kafka.demo.proto.AppointmentProtos.Weekday getWeekday() {
      com.kafka.demo.proto.AppointmentProtos.Weekday result = com.kafka.demo.proto.AppointmentProtos.Weekday.valueOf(weekday_);
      return result == null ? com.kafka.demo.proto.AppointmentProtos.Weekday.SUNDAY : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAppointmentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWeekday()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appointmentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, weekday_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appointmentId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, weekday_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.kafka.demo.proto.AppointmentProtos.Appointment)) {
        return super.equals(obj);
      }
      com.kafka.demo.proto.AppointmentProtos.Appointment other = (com.kafka.demo.proto.AppointmentProtos.Appointment) obj;

      boolean result = true;
      result = result && (hasAppointmentId() == other.hasAppointmentId());
      if (hasAppointmentId()) {
        result = result && getAppointmentId()
            .equals(other.getAppointmentId());
      }
      result = result && (hasUserName() == other.hasUserName());
      if (hasUserName()) {
        result = result && getUserName()
            .equals(other.getUserName());
      }
      result = result && (hasWeekday() == other.hasWeekday());
      if (hasWeekday()) {
        result = result && weekday_ == other.weekday_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasAppointmentId()) {
        hash = (37 * hash) + APPOINTMENTID_FIELD_NUMBER;
        hash = (53 * hash) + getAppointmentId().hashCode();
      }
      if (hasUserName()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasWeekday()) {
        hash = (37 * hash) + WEEKDAY_FIELD_NUMBER;
        hash = (53 * hash) + weekday_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
            java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry
    ) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.kafka.demo.proto.AppointmentProtos.Appointment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.kafka.demo.proto.AppointmentProtos.Appointment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Appointment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Appointment)
        com.kafka.demo.proto.AppointmentProtos.AppointmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kafka.demo.proto.AppointmentProtos.internal_static_Appointment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kafka.demo.proto.AppointmentProtos.internal_static_Appointment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kafka.demo.proto.AppointmentProtos.Appointment.class, com.kafka.demo.proto.AppointmentProtos.Appointment.Builder.class);
      }

      // Construct using com.kafka.demo.proto.AppointmentProtos.Appointment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appointmentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        weekday_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kafka.demo.proto.AppointmentProtos.internal_static_Appointment_descriptor;
      }

      public com.kafka.demo.proto.AppointmentProtos.Appointment getDefaultInstanceForType() {
        return com.kafka.demo.proto.AppointmentProtos.Appointment.getDefaultInstance();
      }

      public com.kafka.demo.proto.AppointmentProtos.Appointment build() {
        com.kafka.demo.proto.AppointmentProtos.Appointment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kafka.demo.proto.AppointmentProtos.Appointment buildPartial() {
        com.kafka.demo.proto.AppointmentProtos.Appointment result = new com.kafka.demo.proto.AppointmentProtos.Appointment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.appointmentId_ = appointmentId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.weekday_ = weekday_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kafka.demo.proto.AppointmentProtos.Appointment) {
          return mergeFrom((com.kafka.demo.proto.AppointmentProtos.Appointment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kafka.demo.proto.AppointmentProtos.Appointment other) {
        if (other == com.kafka.demo.proto.AppointmentProtos.Appointment.getDefaultInstance()) return this;
        if (other.hasAppointmentId()) {
          bitField0_ |= 0x00000001;
          appointmentId_ = other.appointmentId_;
          onChanged();
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasWeekday()) {
          setWeekday(other.getWeekday());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAppointmentId()) {
          return false;
        }
        if (!hasUserName()) {
          return false;
        }
        if (!hasWeekday()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kafka.demo.proto.AppointmentProtos.Appointment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kafka.demo.proto.AppointmentProtos.Appointment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appointmentId_ = "";
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public boolean hasAppointmentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public java.lang.String getAppointmentId() {
        java.lang.Object ref = appointmentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            appointmentId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppointmentIdBytes() {
        java.lang.Object ref = appointmentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appointmentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public Builder setAppointmentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appointmentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public Builder clearAppointmentId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        appointmentId_ = getDefaultInstance().getAppointmentId();
        onChanged();
        return this;
      }
      /**
       * <code>required string appointmentId = 1;</code>
       */
      public Builder setAppointmentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        appointmentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private int weekday_ = 0;
      /**
       * <code>required .Weekday weekday = 3;</code>
       */
      public boolean hasWeekday() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .Weekday weekday = 3;</code>
       */
      public com.kafka.demo.proto.AppointmentProtos.Weekday getWeekday() {
        com.kafka.demo.proto.AppointmentProtos.Weekday result = com.kafka.demo.proto.AppointmentProtos.Weekday.valueOf(weekday_);
        return result == null ? com.kafka.demo.proto.AppointmentProtos.Weekday.SUNDAY : result;
      }
      /**
       * <code>required .Weekday weekday = 3;</code>
       */
      public Builder setWeekday(com.kafka.demo.proto.AppointmentProtos.Weekday value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        weekday_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .Weekday weekday = 3;</code>
       */
      public Builder clearWeekday() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weekday_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Appointment)
    }

    // @@protoc_insertion_point(class_scope:Appointment)
    private static final com.kafka.demo.proto.AppointmentProtos.Appointment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.kafka.demo.proto.AppointmentProtos.Appointment();
    }

    public static com.kafka.demo.proto.AppointmentProtos.Appointment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Appointment>
        PARSER = new com.google.protobuf.AbstractParser<Appointment>() {
      public Appointment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Appointment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Appointment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Appointment> getParserForType() {
      return PARSER;
    }

    public com.kafka.demo.proto.AppointmentProtos.Appointment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Appointment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Appointment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021appointment.proto\"Q\n\013Appointment\022\025\n\rap" +
      "pointmentId\030\001 \002(\t\022\020\n\010userName\030\002 \002(\t\022\031\n\007w" +
      "eekday\030\003 \002(\0162\010.Weekday*e\n\007Weekday\022\n\n\006SUN" +
      "DAY\020\000\022\n\n\006MONDAY\020\001\022\013\n\007TUESDAY\020\002\022\r\n\tWEDNES" +
      "DAY\020\003\022\014\n\010THURSDAY\020\004\022\n\n\006FRIDAY\020\005\022\014\n\010SATUR" +
      "DAY\020\006B)\n\024com.kafka.demo.protoB\021Appointme" +
      "ntProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Appointment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Appointment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Appointment_descriptor,
        new java.lang.String[] { "AppointmentId", "UserName", "Weekday", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
